//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мастер_пол
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMasterFloorUPEntities : DbContext
    {
        public dbMasterFloorUPEntities()
            : base("name=dbMasterFloorUPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Заявки> Заявки { get; set; }
        public DbSet<История_продаж_партнеров> История_продаж_партнеров { get; set; }
        public DbSet<Материалы> Материалы { get; set; }
        public DbSet<Материалы_для_продукции> Материалы_для_продукции { get; set; }
        public DbSet<Партнеры> Партнеры { get; set; }
        public DbSet<Поставщики> Поставщики { get; set; }
        public DbSet<Продукция> Продукция { get; set; }
        public DbSet<Сотрудники> Сотрудники { get; set; }
        public DbSet<Элементы_заявок> Элементы_заявок { get; set; }
    }
}
