//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мастер_пол
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public Заявки()
        {
            this.История_продаж_партнеров = new HashSet<История_продаж_партнеров>();
            this.Элементы_заявок = new HashSet<Элементы_заявок>();
        }
    
        public int ID { get; set; }
        public int id_партнера { get; set; }
        public int id_сотрудника { get; set; }
        public System.DateTime дата_создания { get; set; }
        public string статус { get; set; }
        public Nullable<System.DateTime> дата_предоплаты { get; set; }
        public Nullable<System.DateTime> дата_полной_оплаты { get; set; }
        public string способ_доставки { get; set; }
    
        public virtual Партнеры Партнеры { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual ICollection<История_продаж_партнеров> История_продаж_партнеров { get; set; }
        public virtual ICollection<Элементы_заявок> Элементы_заявок { get; set; }
    }
}
