//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мастер_пол
{
    using System;
    using System.Collections.Generic;
    
    public partial class Материалы
    {
        public Материалы()
        {
            this.Материалы_для_продукции = new HashSet<Материалы_для_продукции>();
        }
    
        public int ID { get; set; }
        public string тип { get; set; }
        public string название { get; set; }
        public int id_поставщика { get; set; }
        public int количество_в_упаковке { get; set; }
        public string единица_измерения { get; set; }
        public decimal стоимость { get; set; }
        public int остаток_на_складе { get; set; }
        public int минимальное_количество { get; set; }
    
        public virtual ICollection<Материалы_для_продукции> Материалы_для_продукции { get; set; }
        public virtual Поставщики Поставщики { get; set; }
    }
}
