//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мастер_пол
{
    using System;
    using System.Collections.Generic;
    
    public partial class Партнеры
    {
        public Партнеры()
        {
            this.Заявки = new HashSet<Заявки>();
        }
    
        public int ID { get; set; }
        public string тип_партнера { get; set; }
        public string название { get; set; }
        public string юр_адрес { get; set; }
        public string ИНН { get; set; }
        public string ФИО_директора { get; set; }
        public string email { get; set; }
        public Nullable<decimal> рейтинг { get; set; }
        public string телефон { get; set; }
    
        public virtual ICollection<Заявки> Заявки { get; set; }
    }
}
