//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мастер_пол
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставщики
    {
        public Поставщики()
        {
            this.Материалы = new HashSet<Материалы>();
        }
    
        public int ID { get; set; }
        public string тип_поставщика { get; set; }
        public string название { get; set; }
        public string ИНН { get; set; }
    
        public virtual ICollection<Материалы> Материалы { get; set; }
    }
}
