//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мастер_пол
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        public Продукция()
        {
            this.Материалы_для_продукции = new HashSet<Материалы_для_продукции>();
            this.Элементы_заявок = new HashSet<Элементы_заявок>();
        }
    
        public int ID { get; set; }
        public string артикул { get; set; }
        public string тип { get; set; }
        public string название { get; set; }
        public string описание { get; set; }
        public decimal мин_цена_партнера { get; set; }
        public int время_изготовления { get; set; }
        public decimal себестоимость { get; set; }
        public int номер_цеха { get; set; }
        public int кол_во_рабочих { get; set; }
    
        public virtual ICollection<Материалы_для_продукции> Материалы_для_продукции { get; set; }
        public virtual ICollection<Элементы_заявок> Элементы_заявок { get; set; }
    }
}
