//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мастер_пол
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public Сотрудники()
        {
            this.Заявки = new HashSet<Заявки>();
        }
    
        public int ID { get; set; }
        public string ФИО { get; set; }
        public System.DateTime дата_рождения { get; set; }
        public string паспортные_данные { get; set; }
        public string банковские_реквизиты { get; set; }
        public bool наличие_семьи { get; set; }
        public string состояние_здоровья { get; set; }
        public string роль { get; set; }
    
        public virtual ICollection<Заявки> Заявки { get; set; }
    }
}
