//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мастер_пол
{
    using System;
    using System.Collections.Generic;
    
    public partial class Элементы_заявок
    {
        public int ID { get; set; }
        public int id_заявки { get; set; }
        public int id_продукции { get; set; }
        public int количество { get; set; }
        public decimal цена { get; set; }
        public System.DateTime дата_производства { get; set; }
    
        public virtual Заявки Заявки { get; set; }
        public virtual Продукция Продукция { get; set; }
    }
}
